CREATE TABLE IF NOT EXISTS Product(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price INT NOT NULL
);
CREATE TABLE IF NOT EXISTS User(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  role ENUM('ADMIN', 'WORKER', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  password VARCHAR(255) NOT NULL,
  phoneNumber VARCHAR(15) NOT NULL
);
CREATE TABLE IF NOT EXISTS BatchProduct(
  batchId INT UNSIGNED NOT NULL,
  productId INT NOT NULL,
  count INT NOT NULL,
  PRIMARY KEY (batchId, productId)
);
CREATE TABLE IF NOT EXISTS ProductStock(
  productId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  count INT NOT NULL,
  updatedBy INT UNSIGNED NOT NULL,
  FOREIGN KEY (updatedBy) REFERENCES User(id)
);
CREATE TABLE IF NOT EXISTS Batch(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  action ENUM('ADD', 'DISPATCH') NOT NULL,
  createdBy INT UNSIGNED NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  FOREIGN KEY (createdBy) REFERENCES User(id)
);